name: Run Cypress tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js via .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Instalar dependências
        run: npm install

      - name: Iniciar servidor local
        run: npm run start &
        shell: bash

      - name: Rodar testes Cypress
        run: npm run cy:run
