name: Executa o teste cypress e publica o relatorio Allure
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js via .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes Cypress com Allure
        
        run: npm run cy:run-allure
        
        continue-on-error: true

      - name: Gerar Relatório Allure
        
        run: npm run allure:generate
        
        if: always()

      - name: Deploy Allure Report to GitHub Pages
        
        uses: peaceiris/actions-gh-pages@v3
        
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          publish_dir: ./allure-report
         
          keep_files: true
